/**
 * Embedded resolved request JSON Schema for third-party connectors.
 *
 * Source of truth: docs/audit/thirdparty_connectors.schema.json (resolved from
 * the Scala case classes + bundled OpenAPI). Polymorphic union discriminated by
 * 'type' (11 subtypes). Surfaced verbatim through describe_thirdparty_connector_schema
 * so the model never guesses the per-subtype structure.
 *
 * Server-only fields '_id' and 'tenant' are intentionally NOT part of the
 * request body.
 */
export const thirdpartyConnectorRequestSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://evertrust.fr/horizon/schemas/thirdparty_connectors.request.json',
  title: 'ThirdPartyConnectors (create/update request body)',
  description:
    "Self-contained resolved request body for POST/PUT /api/v1/thirdparty/connectors. Polymorphic union discriminated by 'type'. Source of truth: Scala case classes (authoritative for requiredness/defaults) reconciled with bundled OpenAPI. Server-only fields '_id' and 'tenant' are intentionally NOT part of the request body (_id stripped via Format.ignoreField; tenant Format never reads input).",
  oneOf: [
    { $ref: '#/$defs/AWSConnector' },
    { $ref: '#/$defs/AzureKeyVaultConnector' },
    { $ref: '#/$defs/F5AS3Connector' },
    { $ref: '#/$defs/F5ClientConnector' },
    { $ref: '#/$defs/GCMConnector' },
    { $ref: '#/$defs/IntuneConnector' },
    { $ref: '#/$defs/IntunePKCSConnector' },
    { $ref: '#/$defs/JamfConnector' },
    { $ref: '#/$defs/LDAPConnector' },
    { $ref: '#/$defs/MSADConnector' },
    { $ref: '#/$defs/NetscalerConnector' },
  ],
  $defs: {
    FiniteDuration: {
      type: 'string',
      description: "Finite Duration string, e.g. '5 seconds'.",
      pattern:
        '^([0-9]+) *(ms|millisecond|milliseconds|s|second|seconds|m|minute|minutes|h|hour|hours|d|day|days)$',
      examples: ['5 seconds'],
    },
    AWSConnector: {
      type: 'object',
      title: 'AWS',
      additionalProperties: false,
      required: ['type', 'name', 'throttleDuration', 'region'],
      properties: {
        type: { const: 'aws' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        proxy: {
          type: ['string', 'null'],
          description: 'Name of an HTTP proxy config.',
        },
        region: { type: 'string' },
        credentials: {
          type: ['string', 'null'],
          description:
            'Name of a password credential (Access Key Id + Secret). Optional: env fallback.',
        },
        resourceGroupName: { type: ['string', 'null'] },
        roleArn: { type: ['string', 'null'] },
        tagKey: { type: ['string', 'null'] },
        tagValue: { type: ['string', 'null'] },
      },
    },
    AzureKeyVaultConnector: {
      type: 'object',
      title: 'Azure Key Vault',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'azureTenant',
        'credentials',
        'vaultBaseUrl',
      ],
      properties: {
        type: { const: 'akv' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        proxy: { type: ['string', 'null'] },
        azureTenant: { type: 'string' },
        appId: {
          type: ['string', 'null'],
          description:
            "Must be absent for password credentials, present for 'credentials' type. Absent from OpenAPI.",
        },
        credentials: {
          type: 'string',
          description:
            'Name of a password/credentials credential (App ID + Key).',
        },
        vaultBaseUrl: { type: 'string' },
        prefix: { type: ['string', 'null'] },
      },
    },
    F5AS3Connector: {
      type: 'object',
      title: 'F5 AS3',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'hostname',
        'credentials',
      ],
      properties: {
        type: { const: 'f5as3' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        proxy: { type: ['string', 'null'] },
        hostname: { type: 'string' },
        credentials: { type: 'string' },
        loginProvider: { type: ['string', 'null'] },
        tlsInsecure: { type: 'boolean', default: false },
        withChain: { type: 'boolean', default: true },
      },
    },
    F5ClientConnector: {
      type: 'object',
      title: 'F5',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'maxStoredCertificatePerHolder',
        'bigIPHostname',
        'credentials',
      ],
      properties: {
        type: { const: 'f5client' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        proxy: { type: ['string', 'null'] },
        maxStoredCertificatePerHolder: {
          type: 'integer',
          description:
            'REQUIRED and positive: constructor throws IllegalArgumentException if None.',
        },
        bigIPHostname: { type: 'string' },
        credentials: { type: 'string' },
        partition: { type: ['string', 'null'] },
        sslParent: { type: ['string', 'null'] },
        prefix: { type: ['string', 'null'] },
        cipherGroup: { type: ['string', 'null'] },
        version: { type: ['string', 'null'] },
        loginProvider: {
          type: ['string', 'null'],
          description: 'Present in Scala, absent from OpenAPI.',
        },
        tlsInsecure: { type: 'boolean', default: false },
        overrideProfileConfiguration: {
          type: 'boolean',
          default: true,
          description: 'Present in Scala, absent from OpenAPI.',
        },
      },
    },
    GCMConnector: {
      type: 'object',
      title: 'GCM',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'credentials',
        'project',
        'location',
      ],
      properties: {
        type: { const: 'gcm' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        proxy: { type: ['string', 'null'] },
        credentials: {
          type: 'string',
          description: "Name of a 'raw' credential (User Account).",
        },
        project: { type: 'string' },
        location: { type: 'string' },
        tagKey: { type: ['string', 'null'] },
        tagValue: { type: ['string', 'null'] },
      },
    },
    IntuneConnector: {
      type: 'object',
      title: 'Intune',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'azureTenant',
        'credentials',
        'legacyRevocationMode',
      ],
      properties: {
        type: { const: 'intune' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        proxy: { type: ['string', 'null'] },
        azureTenant: { type: 'string' },
        appId: {
          type: ['string', 'null'],
          description:
            "Must be absent for password credentials, present for 'credentials' type. Absent from OpenAPI.",
        },
        credentials: { type: 'string' },
        intuneResourceUrl: { type: ['string', 'null'] },
        osQueryString: { type: ['string', 'null'] },
        legacyRevocationMode: { type: 'boolean' },
      },
    },
    IntunePKCSConnector: {
      type: 'object',
      title: 'Intune PKCS',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'maxStoredCertificatePerHolder',
        'azureTenant',
        'credentials',
        'pubKey',
        'keyName',
      ],
      properties: {
        type: { const: 'intunepkcs' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        maxStoredCertificatePerHolder: {
          type: 'integer',
          description:
            'REQUIRED and positive: constructor throws IllegalArgumentException if None.',
        },
        proxy: { type: ['string', 'null'] },
        azureTenant: { type: 'string' },
        appId: {
          type: ['string', 'null'],
          description:
            "Must be absent for password credentials, present for 'credentials' type. Absent from OpenAPI.",
        },
        credentials: { type: 'string' },
        pubKey: { type: 'string' },
        keyName: { type: 'string' },
        providerName: { type: ['string', 'null'] },
        intendedPurpose: { type: ['string', 'null'] },
        searchFilter: { type: ['string', 'null'] },
      },
    },
    JamfConnector: {
      type: 'object',
      title: 'JAMF',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'endpoint',
        'credentials',
      ],
      properties: {
        type: { const: 'jamf' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        proxy: { type: ['string', 'null'] },
        endpoint: { type: 'string' },
        credentials: { type: 'string' },
      },
    },
    LDAPConnector: {
      type: 'object',
      title: 'LDAP',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'maxStoredCertificatePerHolder',
        'hostname',
        'credentials',
        'baseDn',
        'userIdentifierAttribute',
        'certificateAttribute',
      ],
      properties: {
        type: { const: 'ldappub' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        maxStoredCertificatePerHolder: {
          type: 'integer',
          description:
            'REQUIRED and positive: constructor throws InvalidObjectAttributeException if None.',
        },
        proxy: { type: ['string', 'null'] },
        hostname: { type: 'string' },
        port: { type: ['integer', 'null'] },
        credentials: {
          type: 'string',
          description: 'Name of a password credential (login DN + password).',
        },
        baseDn: { type: 'string' },
        filter: { type: ['string', 'null'] },
        certAttr: { type: ['string', 'null'] },
        followReferrals: { type: ['boolean', 'null'] },
        createEntry: {
          type: ['boolean', 'null'],
          description: 'Present in Scala, absent from OpenAPI.',
        },
        userIdentifierAttribute: {
          type: 'string',
          enum: ['CN', 'MAIL', 'UID'],
        },
        certificateAttribute: {
          type: 'string',
          description:
            'Validated dynamically against CFDistinguishedName.DnElement.values() ++ CFSanType.values() in the deployed certfactory (build pins 2.5.18).',
          enum: [
            'CN',
            'UID',
            'SERIALNUMBER',
            'SURNAME',
            'GIVENNAME',
            'T',
            'UNSTRUCTUREDADDRESS',
            'UNSTRUCTUREDNAME',
            'E',
            'OU',
            'ORGANIZATIONIDENTIFIER',
            'PSEUDONYM',
            'UNIQUEIDENTIFIER',
            'STREET',
            'ST',
            'L',
            'O',
            'C',
            'DESCRIPTION',
            'DC',
            'VID',
            'PID',
            'NODEID',
            'FWSIGNINGID',
            'ICACID',
            'RCACID',
            'FABRICID',
            'NOCCAT',
            'RFC822NAME',
            'DNSNAME',
            'URI',
            'IPADDRESS',
            'OTHERNAME_UPN',
            'OTHERNAME_GUID',
            'REGISTERED_ID',
          ],
        },
        tlsInsecure: { type: 'boolean', default: false },
      },
    },
    MSADConnector: {
      type: 'object',
      title: 'Microsoft Active Directory',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'hostname',
        'credentials',
        'baseDn',
      ],
      properties: {
        type: { const: 'msad' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        timeout: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        maxStoredCertificatePerHolder: { type: ['integer', 'null'] },
        proxy: { type: ['string', 'null'] },
        hostname: { type: 'string' },
        port: { type: ['integer', 'null'] },
        credentials: { type: 'string' },
        baseDn: { type: 'string' },
        filter: { type: ['string', 'null'] },
        tlsInsecure: { type: 'boolean', default: false },
      },
    },
    NetscalerConnector: {
      type: 'object',
      title: 'Netscaler',
      additionalProperties: false,
      required: [
        'type',
        'name',
        'throttleDuration',
        'throttleParallelism',
        'timeout',
        'maxStoredCertificatePerHolder',
        'prefix',
        'hostname',
        'credentials',
        'certificateStorePath',
      ],
      properties: {
        type: { const: 'netscaler' },
        name: { type: 'string', description: 'Immutable primary key.' },
        throttleDuration: { $ref: '#/$defs/FiniteDuration' },
        throttleParallelism: { type: 'integer' },
        renewalPeriod: {
          oneOf: [{ $ref: '#/$defs/FiniteDuration' }, { type: 'null' }],
        },
        timeout: {
          allOf: [{ $ref: '#/$defs/FiniteDuration' }],
          description:
            'MANDATORY for netscaler: isTimeoutMandatory=true, validateHttpProxy throws "\'timeout\' is mandatory" if absent. Must be > 0.',
        },
        proxy: { type: ['string', 'null'] },
        maxStoredCertificatePerHolder: {
          type: 'integer',
          description:
            'REQUIRED and positive: forall(_ <= 0) throws (None also rejected).',
        },
        prefix: {
          type: 'string',
          description:
            'Required on Scala case class (OpenAPI wrongly marks nullable).',
        },
        hostname: { type: 'string' },
        credentials: { type: 'string' },
        certificateStorePath: { type: 'string' },
        tlsInsecure: { type: 'boolean', default: false },
      },
    },
  },
} as const;
